##
# Base production configration
# Set up networks to sit behind reverse proxy
##

version: '3.8'

services:
    app:
        environment:
            - NODE_ENV=production
        networks:
            # - reverse-proxy
            - default
    db:
        networks:
            - default
# networks:
# reverse-proxy:
# external: true
