##
# Base production configration
##

version: '3.8'

services:
    app:
        environment:
            - NODE_ENV=production
        networks:
            - default
    db:
        networks:
            - default
        ports:
            - '127.0.0.1:${DB_PORT}:5432'
