version: '3.8'

services:
    db:
        image: postgres:14.5-alpine
        ports:
            - '${DB_PORT}:5432'
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_SCHEMA=${DB_SCHEMA}
            - DB_ADMIN_USER=${DB_ADMIN_USER}
            - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
            - DB_APP_USER=${DB_APP_USER}
            - DB_APP_PASSWORD=${DB_APP_PASSWORD}
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d/ # Run setup scripts
            - pg-data:/var/lib/postgresql/data/ # Make db data persist

    app:
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/${DB_NAME} # necessary to change since communication through container networks
        depends_on:
            - db
        restart: always
        ports:
            - '${APP_PORT}:3000'

volumes:
    pg-data:
