import './globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'AirBnB clone',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Toaster />
                {children}
            </body>
        </html>
    );
}
